### ISSUE TITLE
Error in HMM tracking

### ISSUE THREAD

**Issue by sonovice** [pymatchmaker/matchmaker#11]
Hi and thank you very much for this toolbox and the presentation at this years ISMIR LBD session!

I have a very simple MWE:
```python
from matchmaker import Matchmaker

mm = Matchmaker(
    score_file="bach_846.mid",
    device_name_or_index="MidiKeys",
    input_type="midi",
    feature_type="pianoroll",
    method="hmm",
)
for current_position in mm.run():
    print(current_position)
```

However, if I press a key on my virtual MIDI keyboard, the script crashes with this error message:
```
python test_midi_input.py
/Users/simon/Repos/matchmaker/.venv/lib/python3.12/site-packages/partitura/io/importmidi.py:524: UserWarning: pitch spelling
  warnings.warn("pitch spelling")
/Users/simon/Repos/matchmaker/.venv/lib/python3.12/site-packages/partitura/utils/misc.py:68: UserWarning: voice estimation
  return f(*args, **kwargs)
/Users/simon/Repos/matchmaker/.venv/lib/python3.12/site-packages/partitura/io/importmidi.py:607: UserWarning: create_part
  part = create_part(
/Users/simon/Repos/matchmaker/.venv/lib/python3.12/site-packages/partitura/io/importmidi.py:607: UserWarning: add notes
  part = create_part(
/Users/simon/Repos/matchmaker/.venv/lib/python3.12/site-packages/partitura/io/importmidi.py:607: UserWarning: add time sigs and measures
  part = create_part(
/Users/simon/Repos/matchmaker/.venv/lib/python3.12/site-packages/partitura/io/importmidi.py:607: UserWarning: tie notes
  part = create_part(
/Users/simon/Repos/matchmaker/.venv/lib/python3.12/site-packages/partitura/io/importmidi.py:607: UserWarning: find tuplets
  part = create_part(
/Users/simon/Repos/matchmaker/.venv/lib/python3.12/site-packages/partitura/io/importmidi.py:607: UserWarning: done create_part
  part = create_part(
/Users/simon/Repos/matchmaker/.venv/lib/python3.12/site-packages/scipy/stats/_continuous_distns.py:4167: RuntimeWarning: overflow encountered in exp
  return x - np.exp(x)
/Users/simon/Repos/matchmaker/.venv/lib/python3.12/site-packages/hiddenmarkov/__init__.py:612: RuntimeWarning: divide by zero encountered in log
  self._log_transition_prob = np.log(self._transition_prob)
/Users/simon/Repos/matchmaker/.venv/lib/python3.12/site-packages/hiddenmarkov/__init__.py:600: RuntimeWarning: divide by zero encountered in log
  self._log_init_dist = np.log(self._init_dist)
* Start listening to MIDI stream....
* Stop listening to MIDI stream....                                                                      |
Traceback (most recent call last):
  File "/Users/simon/Repos/matchmaker/test_midi_input.py", line 10, in <module>
    for current_position in mm.run():
  File "/Users/simon/Repos/matchmaker/matchmaker/matchmaker.py", line 206, in run
    for current_frame in self.score_follower.run(verbose=verbose):
  File "/Users/simon/Repos/matchmaker/matchmaker/prob/hmm.py", line 1038, in run
    current_state = self(queue_input)
                    ^^^^^^^^^^^^^^^^^
  File "/Users/simon/Repos/matchmaker/matchmaker/prob/hmm.py", line 914, in __call__
    pitch_obs, ioi_obs = input
    ^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
```

Any help would be highly appreciated.

System info:
Python 3.12 running on macOS 15.1 (arm64)

**Comment by laurenceyoon** [comment]
Hi, thank you for using `matchmaker`!
We are working on an early version for the package, and there are still some parts where the code is not working perfectly. Thank you for reporting the issue, we will fix it and release it with the above issue.
